apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: demo
spec:
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        query: |
          sum(rate(flask_http_request_total{status!~"5.*",job="api",namespace="demo"}[1m]))
          /
          sum(rate(flask_http_request_total{job="api",namespace="demo"}[1m])) or vector(1)
