apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
    helm:
      values: |
        crds:
          enabled: false
        grafana:
          adminPassword: admin
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        alertmanager:
          config:
            global:
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'alertmanager@example.com'
              smtp_require_tls: true
            route:
              group_by: ['alertname']
              group_wait: 5s
              group_interval: 10s
              repeat_interval: 5m
              receiver: 'email-notifications'
            receivers:
            - name: 'email-notifications'
              email_configs:
              - to: 'nguyenphutai.dev@gmail.com'
                send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
